### ISSUE TITLE
마우스는 지원하지 않나요?

### ISSUE THREAD

**Issue by slayers85** [wan2land/unchartedwater2#11]
안녕하세요. 대항해시대2 웹버전 크롬으로 시작해 보았습니다.

마우스를 클릭하면 흰색 동그라미가 퍼지는데 그게 가상조이패드 드래그하는 효과이더군요.

캐릭터 고를 때 마우스로 클릭으로 YES/NO 선택이 안되고 키보드로만 선택이 되던데......

혹시 셋팅이 잘못된 것일까요? 아니면 원래 마우스 클릭 지원불가 게임인지요?

**Comment by wan2land** [comment]
원래 마우스 동작이 되지 않는 것이 정상입니다. 다음 두가지 이유에서 마우스를 차단하였습니다.

*   Canvas 마우스 좌표랑, dosbox로 전달되는 마우스 좌표가 차이가 커서 보정이 필요. (어렵다고 판단)
*   반응형이다 보니 모바일과 데스크탑을 한 소스로 관리 중입니다. 모바일에서는 가상조이패드로 동작하기 때문에 막아두었습니다.
