### ISSUE TITLE
캐릭터 이름 변경방법?

### ISSUE THREAD

**Issue by slayers85** [wan2land/unchartedwater2#12]
PC 크롬 브라우저입니다. 

대항해시대 뉴게임 처음에 캐릭터를 고른 후 이름을 선택하는데요.

자음을 고르면 밑에 라락란랄람랍랏... 나오잖아요?

그런데 아래쪽으로 커서가 내려가지 않아요. 자음 리스트 부분에서만 커서가 움직이요.

방금 글 올렸듯이 마우스는 클릭이 안 되므로 이름설정이 불가능한 상태인데 혹시 해결방법을 알 수 있을지요?

**Comment by wan2land** [comment]
ESC키를 누르면 위아래가 토글 됩니다. :smile: 

생각해보니, 저는 대항해시대2 자체를 마우스 없는 도스 컴퓨터로 입문해서 마우스 없음의 불편함을 느끼지 못했었는데, 이렇게 만들면서 다양한 사람들의 이슈를 들어보니 플레이방식이 다양하다는 생각이 드네요. ㅎㅎ

좋은 이슈 고맙습니다.
