### ISSUE TITLE
모바일 브라우저 (삼성&크롬) 문제점

### ISSUE THREAD

**Issue by slayers85** [wan2land/unchartedwater2#14]
안녕하세요.

갤럭시노트10(안드로이드 버전 10)에서 모바일 실행 시 문제점 제보 드립니다.

1. 삼성브라우저 : 음악이 깨져서 나옵니다. 기본 미디음이 도-레-미-파-솔 이라 가정하면, 도 음이 1번 날 때 동시에 라시도레미 5개 음이 띠디디디디디 하면서 같이 나옵니다. 마찬가지로 레 음이 1번 날 때 시도레미파 음이 띠디디디디디 하면서 같이 나옵니다.
잡음이 엄청 낀 느낌인데 동영상 파일첨부가 안 되어 글로 남깁니다.

2. 크롬 브라우저 : 엔터키를 누를 때마다 화면 밑에 작은 팝업이 올라오는데 크롬마크와 함께 "v0.1.1" 이라고만 적혀 있습니다.
게임할 때 굉장히 거슬리는데 클릭하여 위로 스와이프 해 보니 이렇게 메세지가 나옵니다.
"터치하여 검색에서 선택한 단어와 현재 페이지를 Google 검색에 컨텍스트로 발송하세요. 설정에서 이 기능을 사용 중지할 수 있습니다.  --> 취소/허용"
그만 뜨기게 하기위해 허용을 눌렀으나 팝업이 똑같이 올라오고 이젠 클릭하면 구글에서 "v0.1.1" 을 검색한 결과가 나옵니다.
어떻게 고칠 수 있을까요?

미리 답변에 감사합니다.

**Comment by wan2land** [comment]
1.  저도 dosbox 쪽은 다른 라이브러리에 의존하고 있기 때문에 해당 이슈는 해결할 수 없습니다. ㅠㅠ
2.  갤럭시노트10 환경의 크롬브라우저 스크린샷을 첨부해주시면 해결하는데 도움이 됩니다. :-)  
    (안드로이드 기계가 없습니다..)

**Comment by slayers85** [comment]
크롬브라우저 사진 3장 첨부 드립니다.
​
평소 실행하면 첫번째 사진처럼 아래에 작은 창이 뜨고,
​
위로 올리면 2번째 사진처럼 선택란이 나옵니다.
​
적용하면 그 이후부터는 3번째 사진처럼 검색결과가 뜨네요. (1번 사진 작은 창은 엔터키 누를 때마다 항상 뜸)
​
감사합니다.
​
​
​
​
​
​
​
-----Original Message-----

**Comment by slayers85** [comment]
3번째 사진 누락으로 추가로 보내드립니다.
​
-----Original Message-----

**Comment by wan2land** [comment]
이메일로 답변을 주셔서 스크린샷은 안보이네요. 관련해서 간단한 패치가 되었는데, 한번 확인 부탁드려요. :-)

**Comment by slayers85** [comment]
크롬브라우저에서 하단 팝업 안 뜨고 정상작동합니다.
삼성브라우저 음악깨짐은 그대로 있습니다만 크롬으로 잘 즐기겠습니다.
검사합니다~
