### ISSUE TITLE
저장파일 위치 문의

### ISSUE THREAD

**Issue by lo62ve** [wan2land/unchartedwater2#15]
휴대폰과 PC에서 번갈아가며 이어서 하고 싶은데
데이터가 브라우저에 저장되어 이어하기를 할 수가 없어요
구글드라이브나 드롭박스를 이용하거나 파일로 저장하여 연동할 수 있으면 좋겠습니다. 
아니면 혹시 방법이 있는데 제가 잘 모르는 걸까요?
저장 위치를 변경하는 방법이 있다면 답변주시면 감사하겠습니다.

**Comment by wan2land** [comment]
추후에 대응할 예정입니다.

현재로서는 데스크탑 기준 좌측, 모바일 기준 상단에 위치한 저장과 불러오기 버튼을 통해서 세이브파일을 저장하고 불러올 수 있습니다.
