### ISSUE TITLE
문의 : 선적, 인원할당 등의 계산기패드에서 사칙연산기호 사용

### ISSUE THREAD

**Issue by quitlin99** [wan2land/unchartedwater2#19]
안녕하세요 , 먼저 추억의 겜 올려주셔서 감사 말씀드립니다.

문의사항은 제목 그대로 (제가 잘 몰라 조심스러운데) 식량 물 선적, 선원모집등의 숫자패드에서

사칙연산기호 ( + - * / ) 가 동작이 되지 않는 것 같습니다만

어떻게 사용할 수 있을지 아니면 사용불가인건지 궁금합니다.

시간되실때 답신 주시면 감사하겠습니다.

**Comment by wan2land** [comment]
대응했다고 생각했는데 실제 풀키보드가 없어서 제대로 만들어지지 않았나보네요. 🥲

실행하신 OS와 브라우저 함께 알려주시면 대응할대 도움이 됩니다.

추가로 다음 웹사이트에가면 키보드 번호를 알 수 있습니다. 사칙연산 기호의 숫자코드를 알려주시면 대응하는데 도움이 됩니다.

(예. 사이트에 들어가서 a를 누르면 가운데 65, event.which = 65, event.code = "KeyA" 이런식으로 3개가 나오는데 요걸 각각 알려주시면 됩니다.)

[https://keycode.info/](https://keycode.info/)

**Comment by vampelf** [comment]
숫자패드 결과입니다
+ : 107
- : 109
* : 106
/ : 111

**Comment by quitlin99** [comment]
저도 해봤습니다. OS는 MacOS Ver.11 이고, 브라우저는 MS Edge 입니다. 
/ : 111, event.which=111, event.code="NumpadDivide"
* : 106, event.which=106, event.code="NumpadMultiply"
- : 109, event.which=109, event.code="NumpadSubtract"
+ : 107, event.which=107, event.code="NumpadAdd"
= : 187, event.which=187, event.code="Equal"


수정부탁드리겠습니다!

**Comment by wan2land** [comment]
가상 키보드를 사용해서 테스트 하였고, @vampelf @quitlin99 님이 이야기 주신 키보드 코드와 정확히 일치함을 확인하였습니다. :smile: 

가상환경이긴 하지만 테스트를 진행해보았는데, 정상적으로 동작하였습니다. 선적화면에서 사칙연산 테스트 할 때 입력한 키의 순서는 다음과 같습니다. (숫자와 사칙연산 부호 모두 숫자패드에 있는 키보드를 사용하였습니다.) 주의사항은 계산식 마지막에 엔터키가 아닌 `=` 키를 눌러주어야 합니다.

1.  `5 + 5 =` 를 순서대로 입력하면 10이 나옴.
2.  `5 * 5 =` 를 순서대로 입력하면 25가 나옴.
3.  `5 * 5 =` 를 순서대로 입력하면 25가 나옴.
4.  `14 / 2 =` 를 순서대로 입력하면 7이 나옴.

테스트한 환경과 브라우저는 다음과 같습니다.

1.  macOS bigsur (11.2.3) Chrome / Safari / MS Edge(Mac용도 있더군요?!)
2.  window 7 MS Edge / Chrome

**Comment by wan2land** [comment]
위와 같은 방식으로 숫자패드를 이용해보시고, 동작하지 않으셨다면 어떤 순서대로 숫자패드를 입력했는지 순서대로 이야기주시면 다시한번 테스트 진행해보겠습니다! 고맙습니다. :smile:
