### ISSUE TITLE
더블탭으로 줌 된 후 복원 안됨

### ISSUE THREAD

**Issue by btakeya** [wan2land/unchartedwater2#20]
아이폰 사파리에서 더블탭으로 화면이 줌 된 후 더블탭이나 핀치로 복원이 안됩니다. 제가 브라우저 사용에 미숙해선지 모르겠지만 새로고침해야 초기 상태로 돌아오는데, 그럼 게임 히스토리가 날아가네요... (스크롤도 안돼서 저장바튼 있는 쪽으로 이동도 못합니다)

**Comment by wan2land** [comment]
확인하였습니다. iOS 사파리 자체에서 더블탭 자체를 막는 방법이 없어서 고민중입니다. 빠른시일내에 고쳐놓겠습니다.

**Comment by wan2land** [comment]
패치하였습니다. :-)
