### ISSUE TITLE
정화편 첫 출항시 이상한곳에서 시작함

### ISSUE THREAD

**Issue by kyg5474** [wan2land/unchartedwater2#21]
![image](https://user-images.githubusercontent.com/1156909/118511104-8f180880-b76c-11eb-924e-f63c7fe954e1.png)

![image](https://user-images.githubusercontent.com/1156909/118510911-5ed06a00-b76c-11eb-8b48-a98461c905aa.png)

왜인 것일까요?

**Comment by wan2land** [comment]
세이브파일 1번으로 게임 실행한게 맞으실까요? :-) 새게임으로 시작하신건 아닌지 생각됩니다.

**Comment by kyg5474** [comment]
으앗 브라우저에 저장된 세이브파일은 어떻게 초기화 하죠?

**Comment by wan2land** [comment]
개발자도구 열고, `localStorage.clear()` 를 입력해주세요.
잘 모르시겠다면, 브라우저랑 환경 알려주세요. ㅎㅎ;

**Comment by wan2land** [comment]
아니면, 다른 브라우저에서 실행하시고 드롭박스 세이브파일 동기화 기능을 통해 복원하는 방법도 있습니다.

**Comment by kyg5474** [comment]
![image](https://user-images.githubusercontent.com/1156909/118578554-493c5e00-b7c7-11eb-8003-d142c8bbc706.png)

clear site data라는 기능이 있네요
리셋 되었어요

감사합니다
