### ISSUE TITLE
스토리 진행 오류 문의

### ISSUE THREAD

**Issue by sdsdsy** [wan2land/unchartedwater2#23]
명작을 이렇게 다시 할 수 있게 자리를 만들어 주신 점 정말 감사합니다 ㅠㅠ

예전 추억을 떠올리며, 엉덩이 한번 안떼고 하던 중,....

조안 페레로 스토리 진행중 황태자(?) 정체 밝히는 이벤트에서 아빠 공작 구한 후 리스본 항구에서 황태자 말이 안나오고 진행이 안되는데

시스템  에러일까요??- 다운되는건 아닌데 항구를 못나가요 ㅠㅠ
![대항해시대](https://user-images.githubusercontent.com/87587639/126051747-d3418cee-7e3a-454c-ba2d-b566eb3f2515.jpg)

**Comment by wan2land** [comment]
오리지날 인지 모드인지 알려주셔요. 모드라면 파일이 제대로 올라가있는지 확인해보겠습니다. 😄

게임 자체의 버그라면 그것은 제가 해결할 수 없습니다. 😭

**Comment by sdsdsy** [comment]
그 황태자인가가 선장으로 지정되어있어서 진행이 안되는거였습니다
답장주셔서 감사합니다
좋은 하루되세요~


네이버 메일 앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Changwan Jun" ***@***.***>
받는사람: "wan2land/unchartedwater2" ***@***.***>
참조: "sdsdsy" ***@***.***>,"Author" ***@***.***>
날짜: 2021.07.20 오후 04:18:27 (GMT+09:00)
제목: Re: [wan2land/unchartedwater2] 스토리 진행 오류 문의 (#23)

오리지날 인지 모드인지 알려주셔요. 모드라면 파일이 제대로 올라가있는지 확인해보겠습니다. 😄
게임 자체의 버그라면 그것은 제가 해결할 수 없습니다. 😭
