### ISSUE TITLE
안녕하세요^^

### ISSUE THREAD

**Issue by davidkim1234** [wan2land/unchartedwater2#24]
님 덕분에 너무나 재밋게 하고 있습니다. 
혹시나 해서 여쭙니다.
공명전이나 조조전은 이렇게 브라우저에서 실행할 수 있나요?
혹시 가능한가 싶어서요..ㅠㅠ

**Comment by wan2land** [comment]
윈도우 기반의 고전게임은 아무래도 웹에서 실행하기에 어려운 문제가 있습니다. 🥲 두기런처를 이용하는게 최선인거 같습니다.
