### ISSUE TITLE
마우스 왼쪽, 오른쪽 버튼을 가상키로 넣고 싶습니다.

### ISSUE THREAD

**Issue by rimoris** [wan2land/unchartedwater2#25]
마우스 왼쪽, 오른쪽 버튼을 가상키로 넣고 싶습니다.
해당 가상키를 추가하는 방법을 문의드립니다.

**Comment by wan2land** [comment]
dosbox.js 라는 외부 라이브러리를 이용하여 개발하였는데, 개발 당시 브라우저의 마우스 위치와 도스박스 위의 마우스 위치가 많이 어긋나있어서 사용하기가 어려웠습니다. 🥲

도스박스를 직접 WASM으로 빌드해보려고 하는 계획이 있으나, 해당 부분은 많은 시간이 소요될거 같습니다. 취미로 만든 프로젝트라서 큰 시간을 투여할 수 없다는 점 양해 부탁드립니다. 🙏🙏
