### ISSUE TITLE
드롭박스 세이브 연동 관련입니다.

### ISSUE THREAD

**Issue by dlgustjr14** [wan2land/unchartedwater2#26]
정말 재미있게 하고 있습니다. 감사합니다.

1. 드롭박스 세이브 연동 문제
    - 드롭박스 안에 동일파일명이 있으면 덮어쓰기가 안되는 듯 합니다.

2. 이건 버그가 아닌 요청사항입니다.
    - 가상 키패드에 엔터위에 ESC기가 있는데 ESC키 위치를 바꾸면 좋겠습니다.
    - Enter키 누른다고 누르는데 ESC가 자꾸 미스 클릭되서... 적군 배 한방이면 침몰각인데
      엔터 누른다고 눌렀는데 ESC가 눌러져 공격못하고 턴이 넘어가 깊은 빡침을 느낄때가...
      물론 전적으로 제 잘못이긴 하지만요 ㅎㅎ..

**Comment by wan2land** [comment]
에러 확인했습니다. :-)

```
content.dropboxapi.com/2/files/upload:1          Failed to load resource: the server responded with a status of 409 (Conflict)
app.vue:535 DropboxResponseError: Response failed with a 409 code
    at Dropbox-sdk.min.js:1:30005
```

**Comment by wan2land** [comment]
ESC 키 위치 좌측 상단으로 변경하였습니다.
